on:
  workflow_call:
    inputs:
      toolchain:
        description: 'Rust toolchain version'
        type: string
        default: nightly

name: Code Analysis

jobs:
  rustfmt:
    name: Rust Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: ${{ inputs.toolchain }}
      - run: rustup override set ${{ inputs.toolchain }}
      - uses: Swatinem/rust-cache@v2
      - run: |
          if [ "${{ inputs.toolchain }}" == "nightly" ]; then
            cargo +nightly fmt --all -- --check
          else
            cargo fmt --all -- --check
          fi

  clippy:
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-features --release -- -D warnings
