on:
  workflow_call:

name: Code Analysis

jobs:
  dusk_analyzer:
    name: Dusk Analyzer
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo install --git https://github.com/dusk-network/cargo-dusk-analyzer
      - uses: Swatinem/rust-cache@v2
      - run: cargo dusk-analyzer

  rustfmt:
    name: Rust Format
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt 
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy Check
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-features --release -- -D warnings
