on:
  workflow_call:
    inputs:
      rust_toolchain:
        description: 'Rust toolchain version'
        required: true
        type: string
        default: nightly
      test_flags:
        description: 'Additional flags for cargo test'
        required: false
        type: string
        default: ''

name: Tests

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@${{ inputs.rust_toolchain }}
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --release ${{ inputs.test_flags }}
