on:
  workflow_call:
    inputs:
      test_flags:
        description: 'Additional flags for cargo test'
        required: false
        type: string
        default: ''
      rust_target:
        description: 'Optional Rust target'
        required: false
        type: string

name: Tests

jobs:
  tests:
    name: Run tests
    runs-on: core
    steps:
      - uses: actions/checkout@v3
      - name: Install Optional Rust Target
        if: ${{ inputs.rust_target }}
        run: rustup target add ${{ inputs.rust_target }}
      - uses: Swatinem/rust-cache@v2
      - name: Execute Tests
        run: cargo test --release ${{ inputs.test_flags }}
